spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/demo_api
    username: root
    password: 123456
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/demo_api
    user: root
    password: 123456